---
- name: Rule Test NetworkPolicy
  match:
    rules:
      - DANGER UNWANTED outbound connection destination
    priority: "Critical"
  action:
    name: kubernetes:networkpolicy
    arguments:
  continue: true
  notifiers:
    - slack
# - name: Talon Rule Terminate
#  match:
#    rules:
#      - DANGER UNWANTED outbound connection destination
#    priority: "Critical"
#  action:
#    name: kubernetes:terminate
#    parameters:
#      gracePeriodSeconds: 0
#  continue: false
#  notifiers:
#    - slack
- name: Talon Rule Labelize
  match:
    rules:
      - DANGER UNWANTED outbound connection destination
    priority: "Critical"
  action:
    name: kubernetes:labelize
    arguments:
      suspicious: "true"
      run: ""
  notifiers:
    - slack 
